name: create-bun-exe
on:
    workflow_dispatch:
      inputs:
        tag:
        commit:
          default: "master"
jobs:
  bun-build:
    name: build-bun-exes
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./cli
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.10
      - name: install dependencies
        run: bun install
      - name: build windows
        run: bun build ./index.ts --compile --minify --sourcemap --target=bun-windows-x64 --outfile ${{ github.workspace }}/out/windows64/anywaydata.exe
      - name: check dir  
        run: ls -R ${{ github.workspace }}/out
      - name: workspace dir
        run: ls -R ${{ github.workspace }}
      - uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${ inputs.tag }}
          commit: ${{ inputs.commit }}
          name: Draft Release ${{ github.ref }}
          draft: true
          artifacts:  |
            ${{ github.workspace }}/out/windows64/anywaydata.exe
          body: 'AnyWayData CLI versions'
          allowUpdates: true
    
