name: create-bun-exe
on:
    workflow_dispatch:
      inputs:
        tag:
        commit:
          default: "master"
jobs:
  bun-build:
    name: build-bun-exes
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./cli
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.10
      - name: install dependencies
        run: bun install
      - name: build windows
        run: |
          bun build ./index.ts --compile --minify --sourcemap --target=bun-windows-x64 --outfile ${{ github.workspace }}/out/windows64/anywaydata.exe
          zip -j ${{ github.workspace }}/windows64.zip ${{ github.workspace }}/out/windows64/anywaydata.exe
      - name: build linux-x64
        run: |
          bun build ./index.ts --compile --target=bun-linux-x64 --outfile ${{ github.workspace }}/out/linux-x64/anywaydata
          zip -j ${{ github.workspace }}/linux-x64.zip ${{ github.workspace }}/out/linux-x64/anywaydata
      - name: build linux-arm64
        run: |
          bun build ./index.ts --compile --outfile ${{ github.workspace }}/out/linux-arm64/anywaydata --target=bun-linux-arm64
          zip -j ${{ github.workspace }}/linux-arm64.zip ${{ github.workspace }}/out/linux-arm64/anywaydata
      - name: build mac-x64
        run: |
          bun build ./index.ts --compile --outfile ${{ github.workspace }}/out/macos-x64/anywaydata --target=bun-darwin-x64
          zip -j ${{ github.workspace }}/macos-x64.zip ${{ github.workspace }}/out/macos-x64/anywaydata
      - name: build mac-arm64
        run: |
          bun build ./index.ts --compile --outfile ${{ github.workspace }}/out/macos-arm64/anywaydata --target=bun-darwin-arm64
          zip -j ${{ github.workspace }}/macos-arm64.zip ${{ github.workspace }}/out/macos-arm64/anywaydata
      - name: check dir  
        run: ls -R ${{ github.workspace }}/out
      - uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${ inputs.tag }}
          commit: ${{ inputs.commit }}
          name: Draft Release ${{ github.ref }}
          draft: true
          artifacts:  |
            ${{ github.workspace }}/windows64.zip
            ${{ github.workspace }}/linux-x64.zip
            ${{ github.workspace }}/linux-arm64.zip
            ${{ github.workspace }}/macos-x64.zip
            ${{ github.workspace }}/macos-arm64.zip
          body: 'AnyWayData CLI versions'
          allowUpdates: true
    
